박스오피스 [STEP 3] John
2023newkrew/ios-box-office pull request #10
Opened 2023-01-31 06:33 UTC by limjae

@zdodev 

세번째 PR  올립니다! 😃

## 고민한점

### 1. Dynamic Type

`BoxOfficeListCell`의 모든 텍스트에 Dynamic Type을 적용하여 해당 내용에 따라 Cell의 크기가 변동하도록 노력했습니다.

### 2. DiffableDataSource

`BoxOfficeListCell`에 사용될 Data를 지정하기 위해 기존 `DailyBoxOfficeSearchResult.DailyBoxOffice`중
필요한 property만 모아 `BoxOfficeSummary`을 구현했습니다.

### 3. Extension

전역적으로 쓸 가능성이 있는 Extension의 경우 Extension 폴더에 public으로 구현하였고,
BoxOfficeListViewController에서만 쓸 Extension의 경우 private로 구현하였습니다.

## 궁금한점

### 1. AutoLayout

현재 `BoxOfficeListCell` 에서 accessory와 label의 크기가 충돌나지 않도록
accessory의 가로 길이를 미리 지정하고 이를 Constraint에 반영한 상태입니다.

혹시 UICollectionViewListCell의 Accessory에도 Constraint를 적용 할 수 있는 방법이 있을까요?

2023-02-01 09:33 UTC, zdodev requested changes
안녕하세요. @limjae !

Step 3 기능 명세대로 구현 잘 진행해주셨습니다!

질문에 대한 내용을 포함하여 몇 가지 코멘트를 남겨보았습니다!
확인 부탁드립니다!

2023-02-01 09:33 UTC, zdodev commented on BoxOffice/Model/DailyBoxOfficeSearchResult.swift
> +    func summary() -> BoxOfficeSummary {
`BoxOfficeSummary` 생성을 위한 메서드를 정의해보셨네요!👍

2023-02-01 09:33 UTC, zdodev commented on BoxOffice/Model/BoxOfficeSummary.swift
> +struct BoxOfficeSummary: Hashable {
`Cell` 에서 사용할 모델을 별도로 정의해보셨네요!👍

2023-02-01 09:33 UTC, zdodev commented on BoxOffice/UIComponent/BoxOfficeListCell.swift
> +    private func setHierachy() {
메서드 이름에 오타가 있는 것 같습니다!

2023-02-01 09:33 UTC, zdodev commented on BoxOffice/UIComponent/BoxOfficeListCell.swift
> +        self.addSubview(self.audienceStatisticsLabel)
`Cell` 의 `contentView` 프로퍼티를 사용하지 않은 이유가 궁금합니다!
질문의 `accessory` 와 관련하여 Constraint 문제를 해결할 수 있을 것 같습니다!

2023-02-01 09:33 UTC, zdodev commented on BoxOffice/UIComponent/BoxOfficeListCell.swift
> +        if rankType == "OLD" && rankChange > 0 {
`rankChange > 0` 구문의 의미가 모호한 것 같습니다. 
랭킹의 증가, 감소를 나타낼 수 있는 표현법으로 변경해볼 수 있을까요? 의견이 궁금합니다!

2023-02-01 09:33 UTC, zdodev commented on BoxOffice/UIComponent/BoxOfficeListCell.swift
> +    convenience init(textAlignment: NSTextAlignment, font: UIFont){
`convenience init` 로 중복된 코드를 제거해보셨네요!👍
마지막 `{` 띄어쓰기 오타가 있는 것 같습니다!

2023-02-01 09:33 UTC, zdodev commented on BoxOffice/ViewController/BoxOfficeListViewController.swift
> +    }()
`refresher` 프로퍼티를 클로저를 사용해 초기화하신 이유가 궁금합니다!

2023-02-01 09:33 UTC, zdodev commented on BoxOffice/ViewController/BoxOfficeListViewController.swift
> +                self.refresher.endRefreshing()
만약 네트워크 요청이 실패하거나 에러가 발생하는 경우에 `endRefreshing` 메서드가 실행되지 않을 것 같습니다.
예외의 경우에도 `refresher` 가 종료될 수 있도록 수정해볼 수 있을까요?

2023-02-01 12:57 UTC, limjae commented on BoxOffice/ViewController/BoxOfficeListViewController.swift
> +                self.refresher.endRefreshing()
그 부분은 미처 생각하지 못했습니다. 해당 사항 반영했습니다!

2023-02-01 13:02 UTC, limjae commented on BoxOffice/UIComponent/BoxOfficeListCell.swift
> +        if rankType == "OLD" && rankChange > 0 {
좀 더 명확하게 표현하도록 수정했습니다!

2023-02-01 13:03 UTC, limjae commented on BoxOffice/UIComponent/BoxOfficeListCell.swift
> +        self.addSubview(self.audienceStatisticsLabel)
Cell의 구조를 명확히 파악하지 못해서 생겼던 문제였습니다.
해당 사항을 반영하여 수정했습니다.
감사합니다!

2023-02-01 13:04 UTC, limjae commented on BoxOffice/ViewController/BoxOfficeListViewController.swift
> +    }()
수정했습니다!

2023-02-02 13:48 UTC, zdodev approved these changes
안녕하세요. @limjae !

피드백을 잘 반영하여 코드를 개선해보셨네요!👍
코멘트만 확인하고 넘어가면 될 것 같습니다!
Step 3 진행하시느라 고생하셨습니다.🥳

2023-02-02 13:48 UTC, zdodev commented on BoxOffice/UIComponent/BoxOfficeListCell.swift
> +        self.contentView.addSubview(self.audienceStatisticsLabel)
좋습니다!👍

2023-02-02 13:48 UTC, zdodev commented on BoxOffice/UIComponent/BoxOfficeListCell.swift
> +            switch rankChange.signum() {
`switch` 를 사용하여 개선해보셨네요!👍

2023-02-02 13:48 UTC, zdodev commented on BoxOffice/ViewController/BoxOfficeListViewController.swift
> +    private let refresher: UIRefreshControl = UIRefreshControl()
👍

2023-02-02 13:48 UTC, zdodev commented on BoxOffice/ViewController/BoxOfficeListViewController.swift
> +                self.refresher.endRefreshing()
네트워크 에러에 상관없이 종료하도록 개선해보셨네요!👍

2023-02-02 13:48 UTC, merged