박스오피스 [Step3] Forest
2023newkrew/ios-box-office pull request #11
Opened 2023-02-02 09:11 UTC by forestjae

안녕하세요 라자냐! @wonhee009
개인적인 사정으로 스텝 3 구현이 늦었습니다 ㅜ.ㅜ

이번에도 잘 부탁드립니다.

* 지난 스텝에서 말씀해주신 network 객체의 책임과 설계 관련 부분은 스텝4에서 반영하겠습니다!

## 고민한 점
- MVC 아키텍쳐를 사용하여 구현했습니다.
- Modern Collection View: `UICollectionLayoutListConfiguration`를 사용하여 화면을 구성했습니다.
- DiffableDataSource와 CellConfiguration을 사용했습니다.
- 처음 로딩 시, 당겼다 놓았을때 인디케이터 표시는 CollectionView의 RefreshControl을 사용해서 구현했습니다.
- API Response타입을 그대로 활용하는 것이 아닌, 별도의 Model Entity를 만들어 변환하여 사용하였습니다.
- API 인터페이스를 담당하는 MovieService객체를 ViewController가 사용합니다.
- 어제의 날짜를 받아오기 위해서 현재날짜(`Date()`)에서 3600 * 24 를 빼주는 방법을 사용했습니다.
- NSMutableAttributedString을 사용하여 하나의 레이블로 순위 변동을 나타내는 그림과 글자를 표현했습니다. 

## 질문
- 셀을 구현하는 과정에서, 왼쪽의 순위 표시를 담당하는 스택뷰에 width 제약으로 상수를 주었습니다. 이렇게 하지 않으면 열이 맞지 않는 현상이 발생하더라구요. 혹시 좋은 방법이 있을까요?

감사합니다.

2023-02-03 05:51 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인부탁드립니다.

- 스택뷰에 width를 지정해주지 않는다면 스택뷰의 width는 어떤걸 기준으로 잡힐까요? 스택뷰를 사용하지 않더라도 width를 지정해줘야 모든 cell의 열이 맞을거 같습니다.

2023-02-03 05:51 UTC, wonhee009 commented on BoxOffice/Extension/Date+Extension.swift
> +    }
Date 타입에 extension을 정의하여 모든 Date 타입에서 `yesterday` 프로퍼티를 사용할 수 있을거 같은데요.
모든 Date에서 사용하는 프로퍼티일까요?

2023-02-03 05:51 UTC, wonhee009 commented on BoxOffice/Model/Movie.swift
> +    let staffs: [Staff]
해당 프로퍼티들이 모두 필요한 상황일까요?

2023-02-03 05:51 UTC, wonhee009 commented on BoxOffice/Scene/BoxofficeListContentView.swift
> +
```suggestion
        let label = UILabel()
```

2023-02-03 05:51 UTC, wonhee009 commented on BoxOffice/Scene/BoxofficeListContentView.swift
> +        return stackView
```suggestion
        stackView.axis = .vertical
        return stackView
```

2023-02-03 05:51 UTC, wonhee009 commented on BoxOffice/Scene/BoxofficeListContentView.swift
> +    private func configureRankDescription(isNew: Bool, rankInten: Int) -> NSAttributedString {
`isNew`, `rankInten` 등 입력받은 파라미터에 따라 디자인 요소들이 달라지는거로 이해했습니다.
``` swift
enum -Type {
   case new
   case rank
   ...
}
```
이런식으로 타입을 정해놓고 사용하는건 어떤가요?
enum을 사용하므로써 if-else if 구문 대신 switch를 사용할 수 있는 점도 좋을거 같고, 이후에 다른 타입의 디자인이 추가될 때에도 현재 코드라면 파라미터가 늘어날거 같아서요.

2023-02-03 05:51 UTC, wonhee009 commented on BoxOffice/Scene/BoxofficeViewController.swift
> +    }()
viewDidLoad 시점에 `configureCollectionView()`를 호출하고 있는데요.
`configureCollectionView()`에서 collectionView를 새로 만들어서 지정해주고 있는거로 이해했습니다.
그렇다면 여기서 CollectionView를 미리 만들 필요 없는거 아닌가요?

2023-02-06 01:08 UTC, forestjae commented on BoxOffice/Model/Movie.swift
> +    let staffs: [Staff]
이 타입은 스텝4에서 추가하려고 했었는데, 같이 커밋이 되어버렸네요. 스텝4에서 수정하겠습니다 😂😂

2023-02-06 01:11 UTC, forestjae commented on BoxOffice/Scene/BoxofficeViewController.swift
> +    }()
```
private var collectionView: UICollectionView!
```
암시적 추출을 사용하여 변경했습니다.

2023-02-06 01:12 UTC, forestjae commented on BoxOffice/Scene/BoxofficeListContentView.swift
> +
개행 컨벤션 통일했습니다.

2023-02-06 01:29 UTC, forestjae commented on BoxOffice/Scene/BoxofficeListContentView.swift
> +    private func configureRankDescription(isNew: Bool, rankInten: Int) -> NSAttributedString {
```
    enum RankType: Hashable {
        case new
        case old(rankInten: Int)
    }
```
위와 같은 enum을 만들어서 적용했습니다.

2023-02-06 01:34 UTC, forestjae commented on BoxOffice/Extension/Date+Extension.swift
> +    }
별도의 `DateStore` 네임스페이스를 만들어서 사용하는것으로 변경했습니다 :)

2023-02-06 02:18 UTC, wonhee009 commented on BoxOffice/Network/DateStore.swift
> +}
이런 방식도 좋지만 `DataStore.yesterday`로 사용처에서는 사용할텐데요. 모호한 감이 있을거 같습니다. 해당 프로퍼티를 사용하는 곳이 한정적이라면 사용하는 곳에서
``` swift
private extension Date {
   ...
}
```
이렇게 접근 제한자를 통해 구현하는 방법도 있을거 같습니다.

2023-02-06 02:19 UTC, wonhee009 approved these changes
코멘트 남긴 부분은 다음 스텝에서 다시 생각해주세요. 수고하셨습니다 :)

2023-02-06 02:19 UTC, merged

2023-02-06 02:21 UTC, forestjae commented on BoxOffice/Network/DateStore.swift
> +}
이 방법이 더 좋아보이네요! 수정하겠습니다