BoxOffice [Step3] Summer
2023newkrew/ios-box-office pull request #12
Opened 2023-02-03 01:45 UTC by shinhee-rebecca

안녕하세요 라자냐! @wonhee009

### 고민한 점
1. 화면이 간단하다고 판단되어서 MVC 구조로 구현하였습니다.
2. 처음에 CollectionView가 그려질 때 레이아웃이 한번에 잡히는게 아니라 화면이 버벅이면서 다시 잡힙니다. 보기에 안좋아서 LoadingView를 만들고 처음 레이아웃이 잡히기 전에는 LoadingView가 보이도록 구현하였습니다.
3. 순위 등락 표시를 할 때 하나의 라벨의 text에서 2가지의 색상이 나와서 attributedString을 사용하여 구현하였습니다.

### 궁금한 점
고민한 점 2번의 상황에서 다른 해결방안은 없을까요?

2023-02-03 07:34 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인 부탁드려요.

- 화면이 왜 버벅이면서 잡히는지에 대해서는 원인은 아실까요?

2023-02-03 07:34 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListViewController.swift
> +import XCTest
필요한 import일까요?

2023-02-03 07:34 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListViewController.swift
> +    private var loadingView: LoadingView!
상단의 `refreshControl`은 옵셔널 타입인데 `loadingView`는 !로 정의한 이유가 있을까요?

2023-02-03 07:34 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
로딩뷰 세팅이 완료되고 1초 뒤에는 로딩뷰가 사라지도록 세팅되어져 있는거 같은데요.
API 응답이 오지 않아도 로딩뷰가 사라질 수 있을거 같습니다. 의도하신 동작일까요?

2023-02-03 07:34 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
해당 코드도 동일하게 0.7초 이후에는 refreshControl이 사라지는게 의도한 동작 맞을까요?

2023-02-03 07:34 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListCollectionViewCell.swift
> +    private func configureMovieInfoLabel(audienceCount: String, cumulativeAudience: String) {
String 타입을 파라미터로 받은 후 메서드 내에서 Int로 변환 후 로직에 사용하는거 같은데요.
Int로 변환된 값을 받는 방식은 어떤가요? API Response를 받을 때부터 Int로 전환한다던지...?

2023-02-03 07:34 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListCollectionViewCell.swift
> +    private func configureRankDescriptionLabel(rankOldOrNew: String, rankingChange: String) {
여기도 마찬가지로 String 타입을 파라미터로 받은 후 메서드 내에서 판단한 후 그에 맞는 UI를 그려주는거로 이해했습니다.
``` swift
enum -Type {
   case new
   case ranking
}
```
이런 식으로 UI 타입을 정의하고 타입을 파라미터로 받아서 UI지정해주는건 어떤가요?
enum 사용한다면 if-else if 구문 대신 switch를 사용할 수 있을거 같고, 이후에 다른 UI 타입이 추가된다면 현재 코드에서는 관련한 파라미터가 추가될거 같아서요.

2023-02-03 07:34 UTC, wonhee009 commented on BoxOffice/Extensions/VerticalAlignLabel.swift
> +public class VerticalAlignLabel: UILabel {
해당 클래스를 만든 이유가 궁금합니다.

2023-02-09 01:10 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListViewController.swift
> +import XCTest
어쩌다가 XCTest가 import 되었을까요. 수정했습니다.

2023-02-09 01:16 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListViewController.swift
> +    private var loadingView: LoadingView!
loadingView의 경우 레이아웃을 잡아줄 때 optional chaining이 되는 것을 방지하고자 !로 정의하였습니다. configureLoadingView에서 주입될 것이 확실하다고 생각했습니다. 이렇게 사용하는 것이 위험할까요?

2023-02-09 01:17 UTC, shinhee-rebecca commented on BoxOffice/Extensions/VerticalAlignLabel.swift
> +public class VerticalAlignLabel: UILabel {
UILable의 경우 vertical alignment 속성이 존재하지 않는데 설정이 필요하여서 해당 클래스를 만들게 되었습니다.

2023-02-09 01:42 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
1초뒤에 로딩뷰가 사라지도록 세팅한 것은 collectionView의 레이아웃이 잡힐 시간을 주기 위함이였습니다. 레이아웃이 잡힌 이후에 로딩뷰가 사라지도록 하려면 어떻게 해야할까요? completion handler로도 잘 안되는 것 같습니다.

2023-02-09 02:30 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
dataSource의 apply가 완료된 후에 refreshControl이 사라지도록 개선하였습니다. 다만 이렇게 된 경우에는 completion의 completion으로 코드가 작동되게 되는데 혹시 더 나은 방법이 있을까요?

2023-02-09 02:33 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListCollectionViewCell.swift
> +    private func configureMovieInfoLabel(audienceCount: String, cumulativeAudience: String) {
해당 부분에 대해서는 고민을 했었습니다. 데이터를 받아오는 모델과 프로그램에서 사용하는 모델을 따로 만들지, Struct 내부에 변환 로직을 넣을지 등을 고민했었는데요. 저도 개선이 필요한 부분이라고 생각합니다. 다만 시간 관계상 우선은 이대로 진행하고 여유가 될 때 개선하는 방향으로 해야할 것 같습니다.

2023-02-09 02:34 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListCollectionViewCell.swift
> +    private func configureRankDescriptionLabel(rankOldOrNew: String, rankingChange: String) {
넵! 저도 라자냐의 의견에 적극 동의합니다. 여유가 될 때 개선하도록 하겠습니다.

2023-02-09 02:41 UTC, shinhee-rebecca commented
화면이 버벅이면서 잡히는 이유는 compositional layout의 적용 타이밍 때문인 것 같은데 구체적으로는 모르겠습니다. compositional layout의 적용 타이밍은 어떻게 고려할 수 있을까요?

2023-02-09 04:27 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListViewController.swift
> +    private var loadingView: LoadingView!
하나는 옵셔널이고 하나는 강제 추출된 옵셔널을 사용하셔서 질문 드렸습니다.
!는 어느정도 크래시에서 자유롭지 않다고 생각하는데요. (주입될 것이 확실하다고 생각되어도) ! 사용을 지양하기는 합니다.

2023-02-09 04:29 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
보통은 레이아웃이 잡힌 이후에 로딩뷰가 사라진다기 보다는 네트워킹이 끝나는 시점 (response를 받은 시점)에 로딩뷰를 사라지도록 처리하는거 같습니다. 로딩뷰를 노출시키는 이유가 언제 response가 도착할지 몰라서 아닌가요?

2023-02-09 04:29 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
이 부분 또한 0.7초 이후에는 apply가 완료되었음을 반드시 보장할 수 있나요?

2023-02-09 14:15 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
0.7초 후가 아닌 apply가 완료된 시점에 refresh control이 종료되도록 개선하여서 보장할 수 있습니다.

2023-02-09 14:16 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
네트워킹이 끝나고 1초 정도 후에 레이아웃이 잡히는데 레이아웃이 잡히는 과정이 보기에 안좋아서 이와같이 구성하였습니다. 그럼에도 네트워킹이 끝나는 시점에 로딩뷰를 사라지도록 구현하는 것이 좋을까요? 간단한 수정을 통해 가능합니다...!

2023-02-09 14:16 UTC, shinhee-rebecca commented on BoxOffice/View/BoxOfficeListViewController.swift
> +    private var loadingView: LoadingView!
해당 사항은 수정하겠습니다 : ) 감사합니다!

2023-02-10 01:48 UTC, wonhee009 commented on BoxOffice/View/BoxOfficeListViewController.swift
> +        })
네트워킹 끝나는 시점에 로딩뷰가 세팅되고 그 이후 1초 뒤에 로딩뷰가 사라지는 순서가 맞을까요?

2023-06-12 23:18 UTC, closed without merging