박스오피스 [STEP 4&5] John
2023newkrew/ios-box-office pull request #14
Opened 2023-02-07 01:37 UTC by limjae

@zdodev 

주말에 작업한 코드가 많아 부득이하게 한번에 올립니다🙏

## 고민한점

### 1. AutoLayout(STEP4)

`MovieDetailViewController`에 사용될 이미지의 경우 가로 길이에 맞춰 이미지 비율을 조정하기 위해 intrinsicContentSize를 재정의 하는 DynamicFitImageView를 구현했습니다.

### 2. URLSession(STEP2, 4, 5)

기존 방식은 GCD와 dataTask를 이용하여 네트워크 통신 처리를 해주었습니다.
그러나 이 방법을 유지하면서 다음 Step을 진행하기에는 가독성에 무리가 있다고 판단하여
`APIProvider` 의 로직은 async/await을 통해 로직을 변경하였습니다.

더불어 로직을 변경하면서 더이상 URLSessionCallable Protocol이 무의미하다고 판단하여 삭제하는 동시에 URLSession에 의존적이지 않는 테스트로 변경하였습니다.

### 3. URLCache 정책(STEP 5)

이미지 검색 API의 결과가 바뀔 것을 고려하여 JSON응답의 경우는 앱 실행시 매번 초기화, 이미지의 경우 URL의 결과에 따라 결과가 바뀌는 일이 잦지 않다고 판단하여 초기화하지 않게 설정했습니다.

현재 JSON 응답의 경우 하루정도의 크기를 전부 합산 했을 때 디스크에 1MB 가량 증가하고 이미지의 경우 3MB 가량 증가하고, STEP6에서 여러 날짜의 데이터를 캐싱한다고 가정하면 10배정도의 데이터를 들고 있는 것이 적절하다고 판단하여 10MB, 30MB로 설정했습니다.

디스크의 경우 적절한 예측이 될지는 모르겠지만 메모리 용량이 크지 않은 서버의 가상 메모리를 설정 할 때 1.5~3배 가량 설정 한 경험을 토대로 메모리의 3배를 지정해주었습니다.

### 4. Result Type Extension

ResultType의 경우 값을 받아올 때 switch문을 통해 parsing해주어야하는데, 한쪽 결과가 필요 없는 경우나 반복적인 switch문을 피하기 위해 extension을 추가했습니다.

## 궁금한점

### 1. URLSession(STEP 5)

MovieDetailViewController의 `dataWithContents` 함수 대신 APIProvider를 통해 이미지를 다운로드 할 경우 `Data(contentsOf: url)` 이미지가 열화된 상태로 다운로드 되었습니다. 해당 원인을 찾아보았지만 해결 방안을 찾지 못해 우선 `Data(contentsOf: url)` 를 사용했습니다. URLSession과 Data를 통해 받아오는 데이터의 처리 방법이 다른지 궁금합니다.

### 2. UIRefreshControl.endRefreshing()의 호출 시점(STEP 4)

UI의 변경 이후 UIRefreshControl.endRefreshing()를 호출 할 경우 애니메이션이 부자연스럽게 작동하여 현재 로직은 호출 시점이 데이터를 불러온 이후 호출됩니다. UIRefreshControl.endRefreshing()의 호출 시점은 자연스러운 UI 애니메이션을 고려하여 호출하는 것이 바람직한지, 모든 호출 후 마지막으로 호출하는 방법이 바람직한지 궁금합니다.

### 3. 캐시 정책 최적화

API의 데이터를 캐싱 할 때 현재 기기의 총 메모리, 어떤 API를 캐시 할 것인지, 캐시 데이터의 생존 기간 등 여러 가지를 고려하여 판단해야 한다고 생각합니다. 이와 관련하여 참고 할만한 자료가 있을까요?

2023-02-07 16:26 UTC, zdodev requested changes
안녕하세요!  @limjae !

현재 프로젝트에 이슈가 있는 것 같습니다.
상세 화면으로 전환할 때, 에러가 발생하여 동작하지 않는 부분이 있습니다.
해당 부분 확인 부탁드립니다!

먼저 질문에 대한 제 생각을 적어보았습니다!

❓ URLSession(STEP 5)

- `URLSession` 과 `Data` 의 차이를 말씀하시는 걸까요? 두 개의 동작 방식은 다르지만 응답 값은 다르지 않은 걸로 알고 있습니다! 요청과 응답 값의 차이를 비교해보면 좋을 것 같습니다!

❓ UIRefreshControl.endRefreshing()의 호출 시점(STEP 4)

- 현재 화면을 확인해보지는 못했지만, 이 부분은 기획에 따라 다를 것 같습니다. 개인적으로는 `자연스러운 UI 애니메이션을 고려하여 호출하는 것` 이 바람직하지 않을까 싶습니다!

❓ 캐시 정책 최적화

- 캐시 정책에 대해 명확한 기준이 있지는 않지만, 캐시 정책에 대한 오픈소스 또는 github 구현물을 참고해보면 좋을 것 같습니다!

이 외에 궁금증을 남겨보았습니다!
확인 부탁드립니다~

2023-02-07 16:26 UTC, zdodev commented on BoxOffice/Network/APIProvider.swift
> +        if let cachedResponse =  self.session.configuration.urlCache?.cachedResponse(for: urlRequest) {
`URLCache` 를 사용하여 로컬 캐시를 구현해보셨네요!
모든 네트워크 데이터를 캐싱하는 정책인지 범위가 궁금합니다!
캐싱 데이터의 잔존 기한에 대한 정책을 별도로 확인할 수 있을까요?

2023-02-07 16:26 UTC, zdodev commented on BoxOffice/Network/NetworkCache.swift
> +    static let api: URLCache = {
캐싱 방식 중 `URLCache` 을 선택한 이유가 궁금합니다!

2023-02-07 16:26 UTC, zdodev commented on BoxOffice/UIComponent/MovieDetailRowStackView.swift
> +                             font: .preferredFont(forTextStyle: .body))
`key`, `value` 라는 이름이 모호하지 않을까 싶습니다! 
타이틀이나 제목을 나타낼 수 있는 네이밍은 어떨까요? 의견이 궁금합니다!

2023-02-07 16:26 UTC, zdodev commented on BoxOffice/ViewController/MovieDetailViewController.swift
> +    private let directorStackView: MovieDetailRowStackView = MovieDetailRowStackView()
타입을 명시하거나 생략하는 기준이 궁금합니다!

2023-02-07 16:26 UTC, zdodev commented on BoxOffice/ViewController/MovieDetailViewController.swift
> +    }
`loadData` 메서드를 `viewWillAppear` 메서드에서 구현하신 이유가 있을까요?

2023-02-08 11:03 UTC, limjae commented on BoxOffice/Network/APIProvider.swift
> +        if let cachedResponse =  self.session.configuration.urlCache?.cachedResponse(for: urlRequest) {
현재 프로젝트에서 이미지 다운로드를 제외한 모든 API통신은 API Provider를 사용하고 있고
APIProvider의 session을 외부에서 주입하지 않는 상태라면, APIProvider를 거치는 모든 네트워크 통신의 경우 캐시를 이용하도록 설정했기 때문에 모든 네트워크를 캐싱한다는 정책을 가지고 있습니다.

그리고 기한에 대한 정보는 앱을 끌 때까지 라고 판단하여
NetworkCache.api에서 static으로 지정하였기에 첫 초기화 시점에서 캐시를 삭제하고
`if let cachedResponse =  self.session.configuration.urlCache?.cachedResponse(for: urlRequest)`코드에서 강제로 정보를 참조하고 있기에 따로 명시하지 않았습니다.

만약 강제로 참조하지 않으려면 `startAsyncLoading()`의 해당 로직을 삭제하고
`URLSessionConfiguration` 객체를 설정하는 부분에
response 응답으로 오는 `cache-control` 헤더를 무시하고 캐시를 불러올 수 있는
`config.requestCachePolicy = .returnCacheDataElseLoad`를 추가하는 방법을 고민해보았습니다.
이 방법은 어떠할지 궁금합니다!

```swift
private var session: URLSession = {
        let config = URLSessionConfiguration.default
        config.urlCache = NetworkCache.api
        config.requestCachePolicy = .returnCacheDataElseLoad
        let session = URLSession.init(configuration: config)
        return session
    }()
```

2023-02-08 11:03 UTC, limjae commented on BoxOffice/Network/NetworkCache.swift
> +    static let api: URLCache = {
NSCache의 경우 메모리에만 저장하게되고 URLCache의 경우는 디스크 + 메모리를 사용할 수 있어서 더 활용의 폭이 크다고 판단했습니다. CoreData의 경우는 추가로 구현해야할 요소가 더 많고 URLSession이 반환하는 데이터만을 다루는 경우에 있어서 더 적합하다고 생각하여 URLCache를 적용하였습니다.

2023-02-08 11:03 UTC, limjae commented on BoxOffice/UIComponent/MovieDetailRowStackView.swift
> +                             font: .preferredFont(forTextStyle: .body))
"감독", "제작년도", "감독"과 같은 속성을 공통화하여 표현할 단어가 마땅히 생각나지 않았었습니다.
keyLabel 과 key에 해당하는 내용이 들어가는 valueLabel이 dictionary 형태를 연상하여 이처럼 지었었습니다.
다시 생각해보니 categoryLabel, contentLabel로 변경하는 것이 좋을 것 같다고 생각합니다!

2023-02-09 00:30 UTC, limjae commented on BoxOffice/ViewController/MovieDetailViewController.swift
> +    private let directorStackView: MovieDetailRowStackView = MovieDetailRowStackView()
명시적으로 작성해야 할 때나 원하지 않는 형태가 추론 될 수 있는 경우만 명시하는데 수정중에 놓친 부분 같습니다 감사합니다!

2023-02-09 00:30 UTC, limjae commented on BoxOffice/ViewController/MovieDetailViewController.swift
> +    }
STEP3의 BoxOfficeListViewController에 되돌아오는 경우에 날짜가 바뀐 경우 업데이트 해주기 위해 해당 메서드에 추가했었습니다. MovieDetailViewController를 구현 할 때 이런 이유를 까먹고 관성적으로 적용한 것 같습니다.
수정하겠습니다!

2023-02-09 14:39 UTC, zdodev commented on BoxOffice/Network/APIProvider.swift
> +        if let cachedResponse =  self.session.configuration.urlCache?.cachedResponse(for: urlRequest) {
`returnCacheDataElseLoad` 정책을 사용하는 방법도 좋습니다!👍

2023-02-09 14:46 UTC, zdodev approved these changes
안녕하세요. @limjae !

앱 정상동작 확인하였습니다!
캐시 정책을 사용하여 네트워크 통신하는 부분도 확인하였습니다.👍
궁금증에 대한 좋은 의견을 적어주신 부분도 좋았습니다!

스텝 진행하시느라 고생하셨습니다!🎉

2023-02-09 14:46 UTC, zdodev commented on BoxOffice/ViewController/MovieDetailViewController.swift
>          self.loadData()
👍

2023-02-09 14:46 UTC, zdodev commented on BoxOffice/Network/APIProvider.swift
> +        config.requestCachePolicy = .returnCacheDataElseLoad
해당 정책을 사용하는 방법도 좋습니다!👍

2023-02-09 14:46 UTC, zdodev commented on BoxOffice/UIComponent/MovieDetailRowStackView.swift
> +                                     font: .preferredFont(forTextStyle: .body))
좋습니다!👍

2023-02-09 14:46 UTC, merged