박스오피스 [STEP 1] Volga
2023newkrew/ios-box-office pull request #2
Opened 2023-01-17 01:38 UTC by volgaHwang

@zdodev 
안녕하세요~ 소대!
볼가입니다!

첫 PR 올립니다!

## 고민한점
1. 테스트

Decodable 할 객체의 네이밍을 어떻게 해야할지에 대해 고민했습니다.
json을 보고, json에 해당하는 key Naming을 그대로 따라가야하는게 맞는지?
일단 마음에 드는, 그리고 컨벤션에 대해 잘 모르겠다고 판단하여 일단은 json에서 쓰는 `Key` 네이밍을 그대로 차용했습니다.

## 궁금한점

두가지가 있습니다..!

1. Decodable 객체의 네이밍을 json `key`값을 따서 이름을 짓긴했는데, 이러한 방식이 맞는 방식인지에 대해 확신이 없습니다. 혹시 좋은 네이밍 방식이 따로 있을까요?
2. 굳이 Mock이 필요하지 않을 것 같아서 Test에 parsing 하고 체킹까지 했는데 이러한 방식도 괜찮은지.. 궁금합니다..

감사합니다!!

2023-01-17 15:51 UTC, zdodev requested changes
안녕하세요. @volgaHwang !

Step 1 진행잘해주셨습니다.
모델 타입도 잘 정의해주셨습니다.👍

질문에 대한 제 생각을 말씀드리자면,

❓Decodable 객체의 네이밍을 json key값을 따서 이름을 짓긴했는데, 이러한 방식이 맞는 방식인지에 대해 확신이 없습니다. 혹시 좋은 네이밍 방식이 따로 있을까요?
- json key 값을 참고해서 네이밍을 하는 것도 좋은 방법이라고 생각합니다.👍 `CodingKey` 를 활용해서 의미를 더 뚜렷하게 나타낼 수 있도록 네이밍을 하는 방법도 좋습니다!

❓굳이 Mock이 필요하지 않을 것 같아서 Test에 parsing 하고 체킹까지 했는데 이러한 방식도 괜찮은지.. 궁금합니다..
- Mock 이 필요하지 않다면 굳이 사용할 필요가 없다고 생각합니다.👍

추가로 코멘트 확인 부탁드립니다!

2023-01-17 15:51 UTC, zdodev commented on BoxOffice/Models/BoxOfficeSearchResult.swift
> +    let audienceIncrement: String
`audienceCount` 는 어떨까요? 증가에 대한 의미보다 수에 대한 의미가 더 좋지 않을까 싶습니다!

2023-01-17 16:22 UTC, volgaHwang commented
@zdodev 

안녕하세요~ 소대!
말씀주신대로 숫자 자체에 대한 의미가 더 맞다고 판단해서 네이밍을 변경했습니다!

2023-01-18 13:01 UTC, zdodev approved these changes
안녕하세요. @volgaHwang !

다음 스텝도 화이팅입니다!
고생하셨습니다!

2023-01-18 13:01 UTC, zdodev commented on BoxOffice/Models/BoxOfficeSearchResult.swift
> +    let audienceCountChangeRate: String
👍

2023-01-18 13:01 UTC, merged