Box Office [ STEP1 ] Summer
2023newkrew/ios-box-office pull request #3
Opened 2023-01-17 06:41 UTC by shinhee-rebecca

@wonhee009
안녕하세요! 라자냐! 잘 지내셨죠? 오랜만이에요 : )

### 고민한 점

1. 해당 프로젝트의 Xcode 최소지원 버전이 14.0으로 설정되어 있어서 13.2 버전인 제 Xcode에서는 열리지 않았습니다. macBook과 Xcode를 모두 업데이트하기에는 시간이 너무 오래걸릴 것 같아 해당 프로젝트 패키지의 .pbxproj를 수정하여 Xcode 최소지원 버전을 낮춰주었습니다.
2. Swift Lint를 적용할까 하지 않을까 고민하다가 업무를 하게 되면 Swift Lint를 사용할 일이 별로 없을 것 같고 깔끔한 코드를 작성하는데 도움이 될 것 같아서 이번 프로젝트에서 사용해보기로 결정하였습니다.

### 질문 사항

1. gitignore.io 사이트에 mac, xcode, swift를 검색해서 나온 내용으로 .gitignore 파일을 생성하였습니다. 이외에 gitignore에 들어가면 좋을 것들이 있는지 궁금합니다!
2. Bundle이 무엇인지 정도만 학습하고 Bundle.main.url을 사용하였습니다. Bundle에 관련된 문서들을 다 보자니 너무 많고 지금처럼 제대로 알지도 못하면서 사용하는건 좀 아니라는 생각이 드는데요. 라자냐는 어느정도의 학습 (?) 을 권장하시나요?

2023-01-17 13:07 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인부탁드립니다.

- 프로젝트 구성에 따라 달라지는데요. 코코아팟을 사용한다면 관련 사항 추가하면 됩니다. 이 부분은 프로젝트 스택에 따라 필요한 부분 활용하시면 될거 같습니다.
- 공식문서의 양이 방대하기 때문에 모두 알기는 어렵다고 생각합니다. 프로젝트를 진행하면서 나오는 부분에 대해서만 제대로 학습하면 되지 않을까요?

2023-01-17 13:07 UTC, wonhee009 commented on BoxOffice/Model/DailyBoxOffice.swift
> +    let result: Information
result보다는 `information`은 어떤가요? 실제 `Information` 타입이 갖고 있는 프로퍼티도 information이 더 적합해보여서요.

2023-01-18 00:44 UTC, shinhee-rebecca commented on BoxOffice/Model/DailyBoxOffice.swift
> +    let result: Information
감사합니다! 확인하고 수정하였습니다 : )

2023-01-18 01:57 UTC, wonhee009 approved these changes
수고하셨습니다~

2023-01-18 01:58 UTC, merged