박스오피스 [STEP 1] Forest
2023newkrew/ios-box-office pull request #4
Opened 2023-01-17 08:02 UTC by forestjae

안녕하세요 라자냐! @wonhee009
이번 프로젝트도 잘 부탁드립니다.

## 고민한 점
- Swift 네이밍에 맞춰 API Response 타입을 설계하였습니다. 추후 도메인 로직에서 사용될 모델 엔티티는 별도 타입으로 설계 예정입니다.
- Coding Utility를 별도의 객체로 설계하였습니다. 네트워크 객체에서 이 객체를 사용할 예정입니다.

## 질문
- 현재 매 파싱마다 `JSONDecoder` 인스턴스를 생성하고 있는데요, 이 점이 마음에 걸립니다. 비용이 크지 않아 이런식으로 해도 상관없는지 다른방법은 없는지 궁금합니다.

감사합니다.

2023-01-17 13:16 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인 부탁드려요.

- 파싱할때마다 `JSONDecoder`를 생성하고 있지만 해당 메서드가 완료되면 인스턴스는 해제되어 지금도 괜찮다고 생각합니다. 매번 생성하지 않으려면 싱글톤을 활용하는 방법도 있을거 같습니다.

2023-01-17 13:16 UTC, wonhee009 commented on BoxOffice/BoxofficeResponse.swift
> +struct BoxofficeResponse: Decodable {
`-Response`라고 네이밍한 이유가 있을까요?

2023-01-17 13:16 UTC, wonhee009 commented on BoxOffice/CodingUtility.swift
> +class CodingUtility {
`Coding`이라는 이름이 모호한거 같은데요. 파싱하는데 사용하는 유틸리티인만큼 역할이 잘 드러나는 이름이면 좋을거 같습니다.

2023-01-18 01:49 UTC, forestjae commented on BoxOffice/BoxofficeResponse.swift
> +struct BoxofficeResponse: Decodable {
모델 Entity를 별도로 설계하기 위해 네트워크 응답값을 파싱하는 타입에는 Response 접미어를 사용했습니다.

2023-01-18 02:03 UTC, forestjae commented on BoxOffice/CodingUtility.swift
> +class CodingUtility {
명확한 이름으로 수정했습니다!

2023-01-18 06:43 UTC, wonhee009 approved these changes

2023-01-18 06:43 UTC, merged