박스오피스 [STEP 2] John
2023newkrew/ios-box-office pull request #6
Opened 2023-01-19 08:03 UTC by limjae

박스오피스 [STEP 2] John

@zdodev 

두번째 PR 이어서 올립니다! 😃

- 도전 스텝은 일단 시도해보았으나 좀 더 고민해보겠습니다
- 실행을 위해선 Secret.plist 파일이 필요합니다!!

## 고민한점

### 1. Decodable 객체

`DailyBoxOfficeSearchResult` 와 `MovieDetailResult` 는 의미 없이 `~~Result`로 Wrapping되어 반환되었습니다.
이 후 사용성을 고려하여 CodingKey를 사용하여 구조체의 구조를 간단하게 변환하였습니다.

### 2. 중복 코드 피하기

`DailyBoxOfficeAPI`, `MovieDetailAPI` 의 코드는 중복되는 기능을 수행하는 코드가 많아, `APIDataTaskProvider` 를 통해 공통 기능을 분리하였습니다.

```swift
struct APIDataTaskProvider {
  
		...
  
    func dataTask(completion: @escaping (Data) -> ()) -> URLSessionDataTask? {
        ...
    }
    
    private func urlRequest() -> URLRequest? {
        ...
    }
}

```

### 3. 보안을 위한 .gitignore

public git repository 상에서 노출되면 안되는 값을 Secret.plist에 저장하였고, .gitignore 파일을 추가하여 git에 올라가는 것을 방지하였습니다.

## 궁금한점

### 1. 보안

git에 올라가야하지 말아야할 종류의 일반적인 데이터의 종류와 처리 방식이 궁금합니다!

- 종류 ex) 이번 프로젝트의 예시로는 파라미터 중 Key...
- 방식 ex) Swift 파일에 하드코딩후 gitignore..?, .plist, xcasset의 data에 올리기 등

2023-01-20 13:23 UTC, zdodev requested changes
안녕하세요. @limjae !

Step 2 구현 잘 진행해주셨습니다!
네트워크에 의존하지 않는 테스트 부분도 구현해보셨네요👍

보통 `.gitignore` 는 git 으로 관리하지 않을 부분을 지정하면 될 것 같습니다.
말씀해주신 것처럼 보안에 민감한 파일이나 개인 환경 설정 파일, 라이브러리, 공유하면 안되는 파일 등등 을 지정하면 될 것 같습니다!
민감한 정보를 꼭 사용해야 한다면 별도의 파일로 관리하는 것이 적절할 것 같습니다!

몇 가지 궁금증을 남겨보았습니다!
확인 부탁드립니다!

2023-01-20 13:23 UTC, zdodev commented on BoxOffice/Network/QueryItems.swift
> +protocol QueryItems {
`items: [URLQueryItem]` 프로퍼티에 대한 프로토콜을 구현하신 이유가 궁금합니다!

2023-01-20 13:23 UTC, zdodev commented on BoxOffice/Network/URLSessionCallable.swift
> +}
`URLSession` 에서 실제 네트워킹을 수행하는 `dataTask(with:completionHandler:)` 메서드를 추상화하여 네트워크에 의존하지 않는 테스트를 구현해보셨네요!👍
iOS 13 이후로는 `URLSessionDataTask` 의 `init()` 메서드가 deprecated 되어 다른 방법을 사용하여 네트워크에 의존하지 않는 테스트를 구현할 수 있는데
다른 방법으로 구현할 수 있는 방법도 별도로 알아보면 좋을 것 같습니다!

2023-01-20 13:23 UTC, zdodev commented on BoxOffice/Network/DailyBoxOffice/DailyBoxOfficeAPI.swift
> +struct DailyBoxOfficeAPI {
API 가 추가될 때마다 타입이 하나씩 추가되는 걸까요?
영화 API 에 대한 공통의 타입을 하나로 구현해보는 것은 어떨까요?

2023-01-20 13:23 UTC, zdodev commented on BoxOffice/Network/DailyBoxOffice/DailyBoxOfficeAPIQuery.swift
> +struct DailyBoxOfficeAPIQuery: QueryItems{
띄어쓰기 오타가 있는 것 같습니다!

2023-01-20 13:23 UTC, zdodev commented on BoxOffice/Network/MovieDetail/MovieDetailAPIQuery.swift
> +struct MovieDetailAPIQuery: QueryItems{
띄어쓰기 오타가 있는 것 같습니다!

2023-01-20 13:23 UTC, zdodev commented on BoxOffice/Secret/SecretKey.swift
> +enum SecretKey {
`.plist` 파일 읽는 부분을 별도로 구현해보셨네요.👍

2023-01-20 13:23 UTC, zdodev commented on BoxOfficeTests/APIDataTaskTests.swift
> +                XCTAssertNotNil(parsed)
응답으로 받은 데이터를 검증하는 코드를 추가하는 것은 어떨까요?

2023-01-20 13:23 UTC, zdodev commented on BoxOfficeTests/APIDataTaskTests.swift
> +                XCTAssertNotNil(parsed)
응답으로 받은 데이터를 검증하는 코드를 추가하는 것은 어떨까요?

2023-01-25 05:06 UTC, limjae commented on BoxOffice/Network/QueryItems.swift
> +protocol QueryItems {
처음 생각은 특정 API 구조체에서 Query의 불필요한 입력 범위를 제한하고 싶어서 위와 같이 구현했었습니다.
하지만 아래의 '영화 API 에 대한 공통의 타입을 하나로 구현해보는 것은 어떨까요?' 코멘트를 생각해보니
꼭 프로토콜을 구현할 필요는 없다고 판단하여 APIRequest 열거형 타입으로 모두 통합하였습니다!

2023-01-25 05:10 UTC, limjae commented on BoxOffice/Network/URLSessionCallable.swift
> +}
해당 사항을 고민해보고 URLSession을 Mocking하는 대신 URLSession을 사용하는 APIProvider를 Mocking하는 방향으로 변경했습니다!

2023-01-25 05:10 UTC, limjae commented on BoxOffice/Network/DailyBoxOffice/DailyBoxOfficeAPI.swift
> +struct DailyBoxOfficeAPI {
'items: [URLQueryItem] 프로퍼티에 대한 프로토콜을 구현하신 이유가 궁금합니다!' 항목과 동일하게 수정하였습니다.

2023-01-25 05:11 UTC, limjae commented on BoxOfficeTests/APIDataTaskTests.swift
> +                XCTAssertNotNil(parsed)
추가해보도록 하겠습니다.

2023-01-25 05:11 UTC, limjae commented on BoxOfficeTests/APIDataTaskTests.swift
> +                XCTAssertNotNil(parsed)
추가해보도록 하겠습니다.

2023-01-25 14:15 UTC, zdodev approved these changes
안녕하세요. @limjae !

코멘트에 대한 의견 잘 보았습니다!
추가로 달아드린 코멘트만 확인하면 될 것 같습니다!

Step 2 구현하시느라 고생하셨습니다!👍

2023-01-25 14:15 UTC, zdodev commented on BoxOfficeTests/APIDataTaskTests.swift
> +                }))
데이터를 검증하는 코드를 추가해보셨네요.👍

2023-01-25 14:15 UTC, zdodev commented on BoxOfficeTests/Mock/MockAPIProvider.swift
> +class MockAPIProvider {
`APIProvider` 에 대한 `MockAPIProvider` 구현해보셨네요!👍
현재 구현한 `MockAPIProvider` 으로는 `APIProvider` 가 테스트에 포함되고 있지 않아 `APIProvider` 에서 구현한 로직까지 검증하기는 어려워보입니다.
다음 세션을 참고해보는 것도 좋을 것 같습니다!
[Testing Tips & Tricks](https://developer.apple.com/videos/play/wwdc2018/417)

2023-01-25 14:16 UTC, merged