Box Office [ STEP2 ] Summer
2023newkrew/ios-box-office pull request #7
Opened 2023-01-19 09:00 UTC by shinhee-rebecca

@wonhee009

안녕하세요 라자냐!
어제 오늘은 개인적인 사정으로 (부서내 버디와의 질의응답 시간) 구현량이 많지 않습니다.
우선 한데까지 PR 올리고 네트워크 테스트는 추가로 구현하겠습니다.
많은 조언 부탁드려요 : )

[ 고민한 점 ]
발급받은 API key를 숨기기 위하여 새로운 파일을 생성하고 해당 파일을 gitignore에 추가하였습니다.

[ 질문 사항 ]
NetworkManager가 많이 미흡한데 조언 부탁드립니다.

2023-01-20 10:33 UTC, wonhee009 requested changes
수고하셨습니다~
코멘트 남겨두었으니 확인 부탁드려요~

현재 `NetworkManager.load()`가 API enum 타입을 파라미터로 받고 있어서 해당 메서드는 Movie와 관련된 API를 호출할 때에만 사용할 수 있을거 같습니다.
이 부분 NetworkManager는 어떤 API든 호출할 수 있도록 공통적인 부분으로 분리하는 방식으로 디벨롭할 수 있을거 같습니다. API 호출을 위한 url을 만드는 역할, url을 통해 실제 API 호출하는 역할, 받은 response를 검증하는 역할을 다 분리하는 형식으로요.

2023-01-20 10:33 UTC, wonhee009 commented on BoxOffice/Utility/DateString.swift
> +enum DateString {
`DateString`이라고 네이밍한 이유가 있을까요?
해당 타입은 enum인데 네이밍에 String이 있어 타입이 헷갈릴거 같습니다.

2023-01-20 10:33 UTC, wonhee009 commented on BoxOffice/Utility/DateString.swift
> +                return Date()
iOS15 이하에서는 `.yesterday` 케이스에 대해서는 어제 일자를 못 받을거 같은데 이게 스펙 맞을까요?

2023-01-20 10:33 UTC, wonhee009 commented on BoxOffice/Utility/DateString.swift
> +    }
해당 프로퍼티를 사용하면 포맷팅된 문자열을 반환할거 같은데요. `value`보다는 포맷팅되었음을 알 수 있는 네이밍은 어떨까요?

2023-01-20 10:33 UTC, wonhee009 commented on BoxOffice/Utility/API.swift
> +            return "https://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?"
`dailyBoxOffice`나 `movie`나 동일한데서 API 받아올거 같은데요 . 하나는 www가 있고 하나는 없는거 같습니다.
해당 url들이 맞나요?
둘다 동일하게 www가 있거나 없다면 `-rest/` 이후부터 다른거 같은데 공통화 할 수 있을까요?

2023-01-20 10:33 UTC, wonhee009 commented on BoxOffice/Utility/API.swift
> +            return "https://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?"
`baseURL`이 private이 아녀서 어디서든 접근 가능할거 같은데요. 의도한 부분인가요?

2023-01-20 10:33 UTC, wonhee009 commented on BoxOffice/Network/NetworkManager.swift
> +                return
```suggestion
return completion(.failure(.wrongResponse))
```
이렇게 불가한가요?.?

2023-01-20 10:33 UTC, wonhee009 commented on BoxOffice/Network/NetworkManager.swift
> +                completion(.success(dataString))
data를 String 타입으로 변환 후 반환하는 이유가 있나요?

2023-01-31 05:40 UTC, shinhee-rebecca commented on BoxOffice/Utility/DateString.swift
> +enum DateString {
Date가 지정어여서 Date로 네이밍하지 않기 위해 DateString으로 사용하였습니다. 그런데 라자냐말대로 DateString으로 네이밍하는 것은 혼돈을 줄 수 있을 것 같아 Day로 바꾸었습니다.

2023-01-31 05:45 UTC, shinhee-rebecca commented on BoxOffice/Utility/DateString.swift
> +                return Date()
today와 yesterday 모두 iOS15이하에서도 일자를 받을 수 있도록 수정하였습니다. 감사합니다!

2023-01-31 05:46 UTC, shinhee-rebecca commented on BoxOffice/Utility/DateString.swift
> +    }
수정하였습니다. 감사합니다!

2023-01-31 05:54 UTC, shinhee-rebecca commented on BoxOffice/Utility/API.swift
> +            return "https://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?"
www의 유무가 해당 url에서 데이터를 받아오는데 영향을 끼치지 않는 것 같습니다. 하지만 통일성을 위해 수정하였습니다. 그리고 공통화할 수 있는 url의 앞부분은 따로 뺴내어주었고, private 접근지정자도 붙여주었습니다. 감사합니다 : )

2023-01-31 05:59 UTC, shinhee-rebecca commented on BoxOffice/Network/NetworkManager.swift
> +                return
가능합니다! 개선하였습니다 : )

2023-01-31 06:00 UTC, shinhee-rebecca commented on BoxOffice/Network/NetworkManager.swift
> +                completion(.success(dataString))
사용하는 곳에서 해당 String을 바로 사용할 수 있도록 하기 위함입니다.

2023-01-31 06:19 UTC, shinhee-rebecca commented
상세한 코멘트 감사합니다 라자냐!

2023-02-01 01:53 UTC, wonhee009 approved these changes

2023-02-01 01:53 UTC, merged