박스오피스 [STEP 2] Forest
2023newkrew/ios-box-office pull request #8
Opened 2023-01-19 10:28 UTC by forestjae

안녕하세요 라자냐! @wonhee009
이번 스텝도 잘 부탁드립니다! 

## 고민한 점
### 네트워크
- POP를 활용하여 Network 및 API Service 기능을 여러 계층으로 나누어 구현하였습니다.(VC 혹은 VM에서 MovieService 객체를 사용합니다.)
- 현재 구현한 APIResponse 타입들을 뷰단에서 그대로 사용하지 않고 별도의 타입을 구현할 예정입니다.
### 테스트
- `URLSessionable` protocol을 구현하여 Mock test를 구현해 보았습니다.

## 질문
- Mock과 Stub간의 차이가 궁금합니다. 검색해보니 Mock은 행위에, Stub은 상태를 검증할때 쓰이는 테스트 객체라고 하는데, 실무에서는 어떨 때 사용하는지 예가 궁금합니다.

감사합니다! 새해 복 많이 받으세요.

2023-01-22 04:07 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인 부탁드려요~

프로젝트가 전반적으로 프로토콜을 이용해 레이어가 작게 나눠져 있는거 같은데요. 그런 과정에서 프로토콜을 정의하고 extension으로 기본구현을 하는 식으로 이뤄져 있는거 같습니다. 
``` swift
protocol MovieAPIEndpoint: APIEndpoint, MovieAPIInformationOwner { }
protocol MovieAPIGetEndpoint: MovieAPIEndpoint, APIGetEndpoint { }
```
또한, 그 과정에서 이런식의 코드도 보이는거 같은데요. 
이렇게 구현하신 이유가 따로 있으신지 궁금합니다.

- Mock과 Stub에 대해서는 적어주신대로 사용하는거 같습니다. 이미 보셨을지도 모르지만 [해당 게시글](https://azderica.github.io/00-test-mock-and-stub/)이 잘 설명해주는거 같네요ㅎㅎ 업무하면서 Mock을 더 많이 사용했던거 같습니다.

2023-01-22 04:07 UTC, wonhee009 commented on BoxOffice/Extension/Date+Extension.swift
> +    }
`Literal`보다는 `convertToString` 이나 `convertString`을 많이 사용했던거 같습니다. 이 부분은 스타일 차이이니 알아만 두면 좋을거 같아요~

2023-01-22 04:07 UTC, wonhee009 commented on BoxOffice/Extension/Date+Extension.swift
> +    }
현재 해당 메서드가 Date의 extension에 정의되어 있는데요. 모든 Date 타입이 `yearMonthDay`라는 포맷팅된 형식을 알아야하나요?

2023-01-22 04:07 UTC, wonhee009 commented on BoxOffice/Network/APIGetEndpoint.swift
> +}
GET으로 보낼때 사용하는 protocol로 이해했습니다.
이후에 POST 등과 같이 다름 타입으로 API를 보내게 된다면 `APIPostEndpoint`라는 프로토콜이 추가되는걸까요?
크게 `var method`만 달라지게 될거 같은데 Get, Post를 프로토콜 자체로 나누지 않고 동일한 프로토콜을 사용하되 get, post 등을 API 정의시에 지정해주는건 어떤가요?

2023-01-22 04:07 UTC, wonhee009 commented on BoxOffice/Network/DefaultNetworkProvider.swift
> +final class DefaultNetworkProvider: NetworkProvider {
`Default`라는 prefix가 붙은 몇몇 클래스가 보이는데요. `Default`라고 네이밍한 이유가 있을까요?
`Default`가 있으니 다른 유형의 NetworkProvider가 있을거 같은데 그건 아닌거 같아서 질문 드립니다.

2023-01-22 04:07 UTC, wonhee009 commented on BoxOffice/Network/NetworkProvider.swift
> +}
`NetworkProvider`를 프로토콜로 정의한 후 `request` 메서드에 대해서는 extension으로 기본 구현 하셨는데요. `class`를 이용할 수 있었을거 같은데 프로토콜로 정의한 이유가 궁금합니다.

2023-01-25 02:43 UTC, forestjae commented on BoxOffice/Extension/Date+Extension.swift
> +    }
해당메서드가 굳이 불필요해 보이네요! 삭제하고 Dateformatter를 사용하는 방식으로 변경했습니다.

2023-01-25 02:50 UTC, forestjae commented on BoxOffice/Network/APIGetEndpoint.swift
> +}
계층을 많이 나눠보려는 욕심이 생겨서 과해졌던 것 같습니다. APIGetEndpoint를 삭제하고, 구체 Endpoint 구조체에서 기본값으로 지정해 주는 식으로 변경하였습니다.

2023-01-25 02:52 UTC, forestjae commented on BoxOffice/Network/DefaultNetworkProvider.swift
> +final class DefaultNetworkProvider: NetworkProvider {
다른 Networkprovider가 향후에 추가 될 수 있어서 이렇게 네이밍 하였습니다. 현재 test에서 MockNetworkProvider를 사용하고 있습니다.

2023-01-25 02:52 UTC, forestjae commented on BoxOffice/Network/NetworkProvider.swift
> +}
위에서 말씀드린대로, 여러 종류의 Network provider가 생길 수도 있음을 대비해 프로토콜로 구현하였습니다.

2023-01-25 02:54 UTC, forestjae commented
> 프로젝트가 전반적으로 프로토콜을 이용해 레이어가 작게 나눠져 있는거 같은데요. 그런 과정에서 프로토콜을 정의하고 extension으로 기본구현을 하는 식으로 이뤄져 있는거 같습니다.
> 
> ```swift
> protocol MovieAPIEndpoint: APIEndpoint, MovieAPIInformationOwner { }
> protocol MovieAPIGetEndpoint: MovieAPIEndpoint, APIGetEndpoint { }
> ```
> 
> 또한, 그 과정에서 이런식의 코드도 보이는거 같은데요. 이렇게 구현하신 이유가 따로 있으신지 궁금합니다.

레이어를 작게 나누는 시도를 하다보니, 위 코드같은 경우는 같은 프로토콜을 중복으로 채택하는 꼴이 되었네요. `MovieAPIGetEndpoint` 프로토콜을 삭제하여 수정하였습니다.

2023-01-25 03:10 UTC, wonhee009 commented on BoxOffice/Network/NetworkProvider.swift
> +}
코멘트에 대해서는 이해했습니다. `NetworkProvider`는 만들어진 session을 실행해주고 응답에 따라 값을 return 해주는 역할인거 같은데요. 다음 스텝에서 아래 사항들 한 번 생각해주시면 좋을거 같습니다.
- NetworkProvider가 decoder를 가지면서 디코딩의 역할을 가져가고 있는데요. NetworkProvider가 디코딩 역할을 가져가는게 맞을까요? provider 이름에 맞게 네트워킹에 관련한 역할만 가져가는게 맞지 않을까요?
- 사실상 NetworkProvider의 역할을 `session.dataTask`의 역할을 갖는다고 생각하고, 이미 만들어진 session을 사용하기 때문에 provider가 여러 종류 생길 수 있는지 의문입니다. (session.dataTask가 크게 달라지는 부분은 없을거 같아서요.)

2023-01-25 03:10 UTC, wonhee009 approved these changes
수고하셨습니다 :)
코멘트 남겨두었으니 다음 스텝에서 확인해주세요.

2023-01-25 04:54 UTC, merged