박스오피스 [STEP 3] Volga
2023newkrew/ios-box-office pull request #9
Opened 2023-01-31 02:24 UTC by volgaHwang

@zdodev 

안녕하세요! 소대!

설 연휴는 잘 쉬셨나요?

오늘은, STEP3 PR을 요청 드립니다!

## 고민한 점

이번 스텝도 역시 고민할 거리가 많았습니다..!!

- 최대한 파일을 많이 쪼개기 했습니다.
- Modern CollectionView Implementation을 보고 Layout / Section 구현법을 보고 참조를 많이 했습니다.
- Network 통신 이후 받아온 데이터를 UI에 반영하기 위해 `updateUI()` 메소드를 구현했습니다.
- `BoxOfficeListCell`에 매핑할 `BoxOfficeItem` `Entity`를 생성했습니다.
- `BoxOfficeItem`은 받아오는 `DailyBoxOffice` Modeld을 바로 매핑할수 있게 `Designated Initializer`를 구현했습니다.
- 날짜를 받아오는 포맷이 `Title`과 어제 BoxOfficeList를 받아오기 위한 `Query`에 들어가는 것이 다른 부분에 대해 `Date` Class에 `dayString` 타입 메소드를 구현했고, format이나 날짜에 대한 부분에서는 Enumerate를 추가하여 구현했습니다.
- `Cell`에서 AutoLayout에 의한 리스크를 줄이고자 StackView를 많이 사용 했습니다.

## 궁금한 점

- `refreshControl` 구현한 부분이 있는데, `loadData` 이후에 `endRefreshing()`메소드를 바로 호출 해 주는데, 이 부분이 UX상 맞는지 잘 모르겠습니다.
- 아직까지는? `BoxOfficeListViewController`에 코드가 감당 안될 정도로 많은편은 아니지만 조만간 더 많아질 것 같다는 생각이 드는 구조인데, 이 구조에 확신이 없는것같습니다. 혹시 더 컴팩트하게 줄일 방법이 있을까요?
- `CollectionView`에서 ViewController에 정의한 `createLayout()`을 사용하기 위해서 `lazy var`키워드를 사용했는데 이것도 맞게 사용 한 것인지 잘 모르겠습니다..! 더 좋은 방법이 있을까요?

2023-01-31 14:53 UTC, zdodev requested changes
안녕하세요. @volgaHwang 

이번 설 연휴는 아주 잘보냈습니다🤗
볼가도 즐겨운 연휴보내셨을까요~?

Step 3 구현 잘 진행해주셨습니다!

질문에 대한 제 의견을 적어보았습니다!

❓아직까지는? BoxOfficeListViewController에 코드가 감당 안될 정도로 많은편은 아니지만 조만간 더 많아질 것 같다는 생각이 드는 구조인데, 이 구조에 확신이 없는것같습니다. 혹시 더 컴팩트하게 줄일 방법이 있을까요?
- 현재도 잘 구현해주셨습니다!👍 점점 코드가 복잡해지고 많아질 것 같다는 생각만으로도 좋은 발전이라고 생각합니다! 다음 내용을 고민해보는 것은 어떨까요?
- 어떤 점에서 코드가 많다는 생각이 들었을까요?
- 앞으로 코드가 복잡해진다면 어떠한 점 때문에 복잡해질까요?
- 혹시 `ViewController` 가 많은 역할을 하고 있지는 않을까요?

추가로 기능 명세 중 다음 사항이 구현되지 않은 것 같습니다.
`처음 목록을 로드할 때, 사용자에게 빈 화면만 보여주는 대신, 로드 중임을 알 수 있게 해주세요.`
해당 기능을 구현해볼 수 있을까요?

다른 질문은 코멘트로 작성해보았습니다. 
다른 궁금증과 함께 확인해보면 좋을 것 같습니다!

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Scene/CellConfigurations/BoxOfficeListCell.swift
> +    func configure() {
뷰의 설정을 `configure` 에 작성하신 이유가 있을까요?
설정하는 구문을 뷰 초기화할 때 정의하는 것은 어떨까요?
이외에도 `configure` 메서드에서 많은 일을 처리하고 있는 것 같습니다. 이를 다른 메서드로 분리해서 정의해볼 수 있을까요?

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +    enum Section {
`internal` 접근 수준으로 정의하신 이유가 있을까요?

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +    private lazy var refresh: UIRefreshControl = {
`refresh` 프로퍼티 이름이 모호한 것 같습니다! 더 구체적인 이름을 사용할 수 있을까요?

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +                                              collectionViewLayout: self.createLayout())
해당 방법도 괜찮은 방법이라고 생각합니다!

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +    func loadData() {
`internal` 접근 수준으로 정의하신 이유가 있을까요? 다른 메서드도 확인해보면 좋을 것 같습니다!

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +        refresh.endRefreshing()
`loadData` 메서드가 내부적으로 비동기로 동작하는데 그러면 데이터가 로드되기 전에 `endRefreshing` 메서드가 실행되지 않을까 싶습니다.
비동기 로직이 완료되고 나서 `endRefreshing` 메서드가 실행되도록 변경해보는 것은 어떨까요? 의견이 궁금합니다!

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +    func configureHierarchy() {
`configureConstraints` 이름은 어떨까요?

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Scene/CellConfigurations/BoxOfficeListCell.swift
> +    let accessoryImageView = UIImageView()
`internal` 접근 수준으로 정의하신 이유가 있을까요? 다른 프로퍼티도 확인해보면 좋을 것 같습니다!

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Entity/BoxOfficeItem.swift
> +struct BoxOfficeItem: Hashable {
`Cell` 에서 사용할 모델을 별도로 정의해보셨네요!👍

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Entity/BoxOfficeItem.swift
> +    private let identifier = UUID()
`identifier` 프로퍼티의 용도가 궁금합니다!

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Entity/BoxOfficeItem.swift
> +            return "오늘 \(totalShowCount) / 총 \(totalShowCount)"
오늘 카운트와 총 카운트가 동일합니다!

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Entity/BoxOfficeItem.swift
> +    }
`hash` 메서드를 구현하신 이유가 궁금합니다!

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Entity/BoxOfficeItem.swift
> +private extension String {
`private extension` 으로 한정해보셨네요!👍

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Entity/BoxOfficeItem.swift
> +    var thousandComma: String {
`thousandComma` 이름이 모호할 수 있을 것 같습니다. `locale` 또는 숫자 표기법과 관련된 이름으로 바꿔보는 것은 어떨까요?

2023-01-31 14:53 UTC, zdodev commented on BoxOffice/Entity/BoxOfficeItem.swift
> +        let numberFormmater = NumberFormatter()
`NumberFormatter` 를 사용해보셨네요!👍

2023-01-31 15:19 UTC, volgaHwang commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +    enum Section {
`Modern CollectionView` 에서 Layout 정의 하는 방식을 구현만하고 수정하지 않은 것 같습니다 ㅎㅎ;;

2023-01-31 15:21 UTC, volgaHwang commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +    private lazy var refresh: UIRefreshControl = {
`refreshBoxOfficeList`이 조금 더 구체적이라고 판단이 듭니다 ㅎㅎ

2023-01-31 15:28 UTC, volgaHwang commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +        refresh.endRefreshing()
언급 주신대로 `loadData` 실행 요청 이후 `endRefreshing`이 되서 수행이 이상하게 됩니다 ㅎㅎ
클로져 사용해서 한번해보려고 합니다~

2023-01-31 16:02 UTC, volgaHwang commented on BoxOffice/Entity/BoxOfficeItem.swift
> +    var thousandComma: String {
보통 용어로 thousand separator로 표현을 하는듯 하여 해당 부분 네이밍 변경하겠습니다.

2023-01-31 16:09 UTC, volgaHwang commented on BoxOffice/Entity/BoxOfficeItem.swift
> +    private let identifier = UUID()
밑에 `hash()` 메소드를 작성했던 이유와 동일한 이유일 것 같습니다.
`Hashable` 프로토콜을 채택 할 경우, `hash()` 메소드가 아래 첨부한 사진같이 되어있어서 필요한 메소드로 알고있었습니다.
<img width="711" alt="스크린샷 2023-02-01 오전 1 07 55" src="https://user-images.githubusercontent.com/121410643/215815176-9e1a0ab5-aa32-442c-a2b2-610475a9fc67.png">

그런데, 공식문서를 다시 읽어보니, 
<img width="962" alt="스크린샷 2023-02-01 오전 1 08 47" src="https://user-images.githubusercontent.com/121410643/215815435-8c2d7cf9-50eb-4808-8770-26ff86370234.png">
`Struct` 의 프로퍼티들이 다 `Hashable`한 경우에 해당하므로 딱히 필요가 없다는 것을 확인했습니다 ㅎㅎ;

해당 부분 지워보겠습니다!

2023-01-31 16:09 UTC, volgaHwang commented on BoxOffice/Entity/BoxOfficeItem.swift
> +            return "오늘 \(totalShowCount) / 총 \(totalShowCount)"
헉.. 고쳐야겠네요!

2023-01-31 16:18 UTC, volgaHwang commented
@zdodev 

안녕하세요! 소대!

코멘트 주신 부분들에 대해 검토해보고 수정사항을 반영했습니다.

## 수정사항

- `TodayCount` / `TotalCount` 수정
- 외부에서 접근 할 필요 없는 객체 `property` 접근제한자 추가
- `Computed Property` 네이밍 변경
- `Cell` 의 `Configuration` 역할에 맡게 네이밍 분리
- `BoxOfficeItem` 구조체에서 `Hashable` 프로토콜 채택에 불필요한 `hash()`메소드 + `identifier` 프로퍼티 제거
- 미반영 요구사항 `처음 목록을 로드할 때, 사용자에게 빈 화면만 보여주는 대신, 로드 중임을 알 수 있게 해주세요.` 반영했습니다.
    - `loadData()` 메소드에 `escaping closure`로 `completion` 파라미터 추가하여 `endRefreshing`, `activityIndicator` 정지 시키게 사용

추가적으로 문의주셨던 `hash()`, `identifier` 프로퍼티를 사용했던 이유를 여쭤보셨는데 조사해보니 불필요한 이유를 찾아서 해당 내용을 대신 코멘트로 남겼습니다!

2023-02-01 09:47 UTC, zdodev approved these changes
안녕하세요. @volgaHwang !

피드백 반영된 부분 잘 확인하였습니다!👍

추가적으로, 복잡해지고 비대해지는 `ViewController` 문제를 해결하기 위한 많은 방법이 존재합니다.
`ViewController` 를 어떻게 하면 확장 가능하면서 가독성 있게 구현해나갈 수 있을지 먼저 고민해 보고 이를 해결하기 위한 방법들을 보면 더욱 좋지 않을까 싶습니다!

Step 3 진행하시느라 고생하셨습니다!👍

2023-02-01 09:47 UTC, zdodev commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +    private lazy var refreshBoxOfficeList: UIRefreshControl = {
좋습니다!👍

2023-02-01 09:47 UTC, zdodev commented on BoxOffice/Scene/BoxOfficeListViewController.swift
> +        }
클로저를 사용하여 해결해보셨네요!👍

2023-02-01 09:47 UTC, zdodev commented on BoxOffice/Entity/BoxOfficeItem.swift
> +    private let identifier = UUID()
질문의 의도를 잘 파악해주셨습니다!🤗
공식문서의 추가내용 학습까지 좋습니다!👍

2023-02-01 09:47 UTC, merged